ALTER TABLE designs
  ADD COLUMN IF NOT EXISTS gradient_from TEXT NOT NULL DEFAULT '#edffef',
  ADD COLUMN IF NOT EXISTS gradient_to TEXT NOT NULL DEFAULT '#0a844a',
  ADD COLUMN IF NOT EXISTS gradient_angle INTEGER NOT NULL DEFAULT 135,
  ADD COLUMN IF NOT EXISTS gradient_animated BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS font_family TEXT NOT NULL DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS font_weight INTEGER NOT NULL DEFAULT 700,
  ADD COLUMN IF NOT EXISTS font_size INTEGER NOT NULL DEFAULT 100;

ALTER TABLE cards
  ADD COLUMN IF NOT EXISTS vcf_button JSONB NOT NULL DEFAULT '{"enabled":true,"label":"Скачать VCF"}'::jsonb;
